smileezcron_cron:
    path: /cron/{tabItem}/tab
    defaults: { _controller: smile.cron.controller.cron:cronAction, tabItem: "status" }
    requirements:
        tabItem: "[a-z]+"

smileezcron_cron_edit:
    path: /cron/edit
    methods: 'POST'
    defaults: { _controller: smile.cron.controller.cron.crons:editAction }
