smileezcron_cron:
    path: /cron/{tabItem}
    defaults: { _controller: smile.cron.controller.cron:cronAction, tabItem: "status" }
    requirements:
        tabItem: "[a-z]+"

smileezcron_cron_edit:
    path: /cron/edit/{alias}
    defaults: { _controller: smile.cron.controller.cron.crons:editAction }
    requirements:
        alias: "[a-z]+"
